### ISSUE TITLE
Data type that translates DVs correctly

### ISSUE THREAD

**Issue by Scotts-Thoughts** [gamehook-io/gamehook#17]
Byte: FF
DV1: 15
DV2: 15
Uses the first character as the first DV and the second character as the second DV

Calculations to isolate the value of the two digits of the byte are:
Byte Digit 1: (Javascript)
`                dvPosA(y) {
                    dvValue = (y - (y % 16))/16
                    return dvValue
                }`
`                dvPosB(y) {
                    return y % 16
                }`

**Comment by flamesage** [comment]
I think technically these are called nybbles.
 
https://en.m.wikipedia.org/wiki/Nibble

However it would probably be more flexible to have a post processor expression that will let you do the basic math.

**Comment by Scotts-Thoughts** [comment]
Yeah, that is what I'm suggesting. Use a post-processor to calculate the nybbles.

**Comment by Scotts-Thoughts** [comment]
Resolved. Post-processor does this now
