### ISSUE TITLE
Can't map the enemy held item in the firered or emerald battle structure

### ISSUE THREAD

**Issue by Speedrunner0218** [gamehook-io/gamehook#21]
When I try to map the held item of the enemy pokemon in the battle structure, the mapper loads, and then crashes. It doesn't do it with "yourPokemon" current held item. Just the enemy's. 

Firered address: 0x02023C6A, size: 2
Emerald address: 0x0202410A, size: 2

**Comment by Scotts-Thoughts** [comment]
After the crash, what does the Gamehook log say?

**Comment by Scotts-Thoughts** [comment]
`      heldItem: { offset: 45, type: "reference", size: 2, reference: "items" }`

Ensure to use { } for properties, not ( )

**Comment by Scotts-Thoughts** [comment]
Was a bracket syntax error - closing this issue.
