### ISSUE TITLE
Pokemon Crystal Mapper Enemy Type Missing

### ISSUE THREAD

**Issue by TheBest100028** [gamehook-io/gamehook#39]
battle -> enemyPokemon -> type1 /type2
It would benefit me greatly if these could be added to the Mapper.
They are in the generation one mapper, so it would be a smooth transition.

Also on a side note,
battle -> enemyPokemon -> moves1 should be move1 to keep with consistency. I brought this up to scott, but never made it a ticket.

**Comment by flamesage** [comment]
This should now be resolved.

https://github.com/gamehook-io/mappers/commit/2190dff2faa5a6d7a2b28a12b28208197415d6e8

Please let me know if I can close this.
