### ISSUE TITLE
On Linux, two gamehook.log files are created

### ISSUE THREAD

**Issue by flamesage** [gamehook-io/gamehook#40]
This is likely a case-sensitivity issue which doesn't appear on Windows.

Starting GameHook created two files in the same binary directory:
GameHook.log
gamehook.log

Only the gamehook.log file was populated with data.

**Comment by DSuenkel88** [comment]
I can confirm this, running GameHook on Fedora 36.

**Comment by flamesage** [comment]
@DSuenkel88 This should be fixed now with the latest version -- can you confirm?

**Comment by DSuenkel88** [comment]
I tested 2024.1.10.1 and it does not generate any log files at all.

**Comment by flamesage** [comment]
Next to the binary that should be expected. 

Could you check ~/.config/GameHook ?

**Comment by DSuenkel88** [comment]
Checked it and yes, in ~/.config/GameHook I found a GameHook.log, populated with log data.

**Comment by flamesage** [comment]
Cool. Thanks!
Confirmed issue is resolved.
