### ISSUE TITLE
Value Editing Error Due to Termination Value

### ISSUE THREAD

**Issue by Scotts-Thoughts** [gamehook-io/gamehook#46]
In some cases where the value is a string a termination character is required. For example, in Pokemon Yellow the player's name must be valued with a byte value of 0x50. Without this termination character the player name spills over and gets very glitchy.

This also occurs with Pokemon Nicknames. (Likely all other strings like this.)

**Comment by flamesage** [comment]
This likely will require an additional property in the mapper to determine if the string should be null terminated.

**Comment by Scotts-Thoughts** [comment]
This has been resolved. The first entry in the reference list, if assigned null, will be used as the terminator for strings.
