### ISSUE TITLE
Value Editing on Properties with Post-Processors

### ISSUE THREAD

**Issue by Scotts-Thoughts** [gamehook-io/gamehook#47]
For example these two properties share the same byte. Each value is a nybble (1 digit of the byte, a value ranging from 0-15) and these post processors return those values.
```
dvAttack:  { offset: 27, type: "int", postprocessor: "(x - (x % 16))/16" }
dvDefense: { offset: 27, type: "int", postprocessor: "x % 16" }
```
When editing the value Gamehook erroneously sets the value of the byte to the input value rather than setting the value of the nybble. In this case if dvAttack is 15 and dvDefense is 15 and the user value-edits the dvAttack input a value of 10, the entire byte is set to 10 resulting in dvAttack being set to 0 and dvDefense being set to 10.

Possible solutions:
- Implement a nybble type.
- Calculate the value of the nybble from the user input value and set the byte accordingly respecting the value of the other nybble.

I have confirmed this issue is also present with the following properties:
- player.team.0.move1ppUp

**Comment by flamesage** [comment]
Likely solution here would be to rename postprocessor to postprocessorRead and create a postprocessorWrite.

**Comment by Scotts-Thoughts** [comment]
That works.
