### ISSUE TITLE
Editing stats has an endian problem

### ISSUE THREAD

**Issue by Scotts-Thoughts** [gamehook-io/gamehook#49]
Editing the property:

`defense: { offset: 38, type: "int", size: 2, description: "The Attack stat as it appears in the Pokemon's summary page in game" }`

With a value of 76 returns: 19456 (Bytes: 0x4C, 0x00) These bytes are in the incorrect order.

Likely need contextual endianness based on the platform.

**Comment by flamesage** [comment]
Confirmed.

**Comment by flamesage** [comment]
Can you retest this on 2023.3.19.3 for me?

**Comment by Scotts-Thoughts** [comment]
Resolved.
