### ISSUE TITLE
Two typos, four oversights, a double entry in Mappers/GB/pokemon_red_blue.yml and a remark regarding dvHP

### ISSUE THREAD

**Issue by DSuenkel88** [gamehook-io/gamehook#53]
1. In "properties" under "statusConditions" the occurence 0x03 of "Asleep" is incorrectly spelled "Alseep" and under "tempStatusBadPoison"->0x01 "Badly Poisoned" is misspelled as "Badly Posioned".

2. The descriptions for macros->pokemonInParty->defense, special and speed (ll. 19-21) describe the correlating stat as "Attack".

3. The key "properties" contains the key "trashCanFlags" two times (ll. 720 & 743).

4. In case it is not known, the DV for HP is calculated from the other four DVs (s. https://www.smogon.com/ingame/guides/rby_gsc_stats#hpdv).

It can be constructed by looking at the DV as binary data, here an example:
`<table>
<tr><th></th><th>DV (Decimal)</th><th>DV (Binary)</th></tr>
<tr><td>ATK</td><td>12</td><td>110<b>0</b></td></tr>
<tr><td>DEF</td><td>7</td><td>011<b>1</b></td></tr>
<tr><td>SPD</td><td>8</td><td>100<b>0</td></tr>
<tr><td>SPC</td><td>15</td><td>111<b>1</b></td></tr>
<tr><td><b>HP</b></td><td><b>5</b></td><td>0101 (ATK-DEF-SPC-DEF)</td></tr>
</table>`
Each first bit (the rightmost ones, here bold) of ATK, DEF, SPD and SPC together equal to the DV for HP.
I only know of a german website as a source: https://pokewiki.de/Individuelle_St%C3%A4rken#Erste_und_zweite_Generation

This is my unmodified pokemon_red_blue.yml for reference:
[pokemon_red_blue.zip](https://github.com/gamehook-io/gamehook/files/11646667/pokemon_red_blue.zip)

Here is my version of the mapper file, in which I corrected those mistakes:
[pokemon_red_blue_modified.zip](https://github.com/gamehook-io/gamehook/files/11647310/pokemon_red_blue_modified.zip)

**Comment by flamesage** [comment]
@Scotts-Thoughts Can you review these and apply these changes to the XML mapper only?

**Comment by DSuenkel88** [comment]
Oh! Yes, I can and I will. Did not expect an answer so soon.

**Comment by flamesage** [comment]
Ill be pushing out an update in a few days to address DVs -- I'll be adding a new Nybble type which should allow you to do "half" bytes.

**Comment by DSuenkel88** [comment]
Nice :)

Oh, okay, that's where those XMLs are coming from :) Seems like a good choice.

The mistakes I found in pokemon_red_blue.xml are also present in pokemon_yellow (xml and yml) - with the exception of the trashCanFlags dublicate, which only exists in the XML version.

**Comment by Scotts-Thoughts** [comment]
Fixes to Deprecated mappers will be included in the next release.
